### ISSUE TITLE
Weekly scrum - Feb. 28th, 2015

### ISSUE THREAD

**Issue by GoodOlChuck** [kevincox/social-wiki#1]
- what have I done this week ?
- what will I do next week ?
- what is holding me back ? (optional)

**Comment by GoodOlChuck** [comment]
what have I done this week? I have entered in the milestones on github to plan out the implementation of the project. I have also added various issues that need to be implemented towards the completion of milestone 2.
what will I do next week? I will begin implementation and contribute to one of the issues in the issue tracker towards the completion of milestone 2.

**Comment by kevincox** [comment]
- Bootstrap the repository including CI and auto-deploy to hosting.
- Start preparing the models.
- Nothing.

**Comment by ZachDFK** [comment]
- Created User issues. Sync up with team. Signed up on Heroku.
- Setting up environment. Meet up with the team on what to do next.
- Not really anything at this point

**Comment by matthewcrooke1** [comment]
- Submitted milestone on cuLearn
- Brainstorm ideas and work on open issues
- Nothing
