### ISSUE TITLE
Connection to localhost cannot be established

### ISSUE THREAD

**Issue by ZachDFK** [kevincox/social-wiki#11]
After making a scaffold for, I attempted to make a connection to view user index
routes.rb have been set to

```
...
resources :users 
get 'users' => 'users#index'
...
```

after running command: 

> bundle exec rails server&

the following was outputted:

> => Booting WEBrick
> => Rails 4.2.5.1 application starting in development on http://localhost:3000
> => Run `rails server -h` for more startup options
> => Ctrl-C to shutdown server
> [2016-03-03 16:38:42] INFO  WEBrick 1.3.1
> [2016-03-03 16:38:42] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
> [2016-03-03 16:38:42] INFO  WEBrick::HTTPServer#start: pid=2613 port=3000

when trying to connect to http://127.0.0.1:3000/users

Firefox gives a problem loading error  saying connection is reset

**Comment by ZachDFK** [comment]
According to @GoodOlChuck this issue also happens even without change to any files. 
no default rails page shows up for http://localhost:3000 like it should

**Comment by GoodOlChuck** [comment]
I found a solution on stack exchange: http://stackoverflow.com/questions/27627286/cant-connect-localhost3000-ruby-on-rails-in-vagrant

Seemingly running rails server with 'rails s -b 0.0.0.0' works.

We need to edit '/config/boot.rb' to bind 0.0.0.0 so that we can run rails s without '-b 0.0.0.0'.
