### ISSUE TITLE
Weekly scrum - Mar. 6th, 2016

### ISSUE THREAD

**Issue by GoodOlChuck** [kevincox/social-wiki#13]
what have I done this week ?
what will I do next week ?
what is holding me back ? (optional)

**Comment by kevincox** [comment]
- I set up heroku to run on the puma webserver and finished up some CI and tooling work.
- Probably start coding on the project itself.
- We need to get the foundation in before everyone can start working in parallel and that appears to have been delayed,

**Comment by matthewcrooke1** [comment]
- Created the model for the post feature
- Help integrate the different parts and get the base project running
- As mentioned the project needs a foundation so producing work alone will be easier

**Comment by GoodOlChuck** [comment]
- Worked on fixing localhost connection issue.
- Start working on the view.
- Model needs to be completed and different parts need to be integrated.

**Comment by ZachDFK** [comment]
Worked on a user scaffold
Make a sign up page for users, make a way for user to log in, user to add post/comments
 Nothing holding back other than other classes work
