### ISSUE TITLE
heroku down?

### ISSUE THREAD

**Issue by ntartania** [kevincox/social-wiki#15]
as of now (march 9th, 3pm), heroku app is down or not deployed. Or the link given in milestone 1 was incorrect.
![snapshot1](https://cloud.githubusercontent.com/assets/766540/13649144/2b2ec96e-e60a-11e5-9c4d-273b6e2c9dee.png)

**Comment by kevincox** [comment]
It's not down. There are just no pages yet. That's a 404.

**Comment by kevincox** [comment]
Pages coming soon!

**Comment by ntartania** [comment]
milestone 1 required 'at least a static home page'...

**Comment by kevincox** [comment]
Does an error page count as "a static home page?"

**Comment by ntartania** [comment]
:-/
I guess it does if you wrote it.

**Comment by ntartania** [comment]
Just add that static page and close the issue...

I've just been going over the projects and found that zero projects have any functionality (aside from static home pages) out in production yet, so that's a little frustrating.

**Comment by kevincox** [comment]
Yup, someone has a PR open and it is just going through reviews so we should have a homepage soon.

**Comment by kevincox** [comment]
Oops, I linked the wrong PR.

**Comment by kevincox** [comment]
However that PR that was merged did add a page, just not an index page: https://social-wiki.herokuapp.com/users
