### ISSUE TITLE
Store passwords properly.

### ISSUE THREAD

**Issue by kevincox** [kevincox/social-wiki#17]
Sorry, my mistake. I should have never gave a thumbs up to #3. It should use rails user functionality so that things are actually done securely.

@ZachDFK

**Comment by ZachDFK** [comment]
Alright I'll fix it, but just so were on the same page, the passwords to be stored as a hash? or does rails have a specific function to make their stuff safe

**Comment by kevincox** [comment]
I'm 99.999% sure rails has an authentication framework that does everything for you. Please never manage passwords yourself.
