### ISSUE TITLE
Submit project info text file to CULearn

### ISSUE THREAD

**Issue by GoodOlChuck** [kevincox/social-wiki#5]
One team member should submit to CULearn a short text with your team members and
topic, and a link to the github repo for your project.

Topic: Social Wiki
Group Members: Charles Wright (@goodolchuck), Kevin Cox (@kevincox), Matthew Crooke (@matthewcrooke1), and Zacharie Gauthier (@ZachDFK).
GitHub Repo: https://github.com/kevincox/social-wiki.git

**Comment by kevincox** [comment]
Done
